import type { GenerateRequest, GenerateResponse, LLMProvider } from '../types'

/**
 * 키 없이 동작하는 시뮬레이션 프로바이더.
 * 스트리밍·캐싱·UI를 실제 키 없이 검증할 수 있게 한다.
 * systemPrompt를 근거로 언어/콘텐츠 유형을 추정해 그럴듯한 미리보기를 생성한다.
 */
export const mockAdapter: LLMProvider = {
  async generate(req) {
    const start = Date.now()
    const text = buildMockText(req)
    return {
      text,
      usage: {
        inputTokens: Math.ceil(req.prompt.length / 4),
        outputTokens: Math.ceil(text.length / 4),
        totalTokens: Math.ceil((req.prompt.length + text.length) / 4),
      },
      finishReason: 'stop',
      provider: 'mock',
      model: req.model,
      latency: Date.now() - start,
    } satisfies GenerateResponse
  },

  async *stream(req) {
    const text = buildMockText(req)
    // 단어 단위로 지연 방출 → 실제 스트리밍처럼 표시
    const tokens = text.match(/\s*\S+/g) ?? [text]
    for (const tok of tokens) {
      if (req.signal?.aborted) return
      await delay(14)
      yield tok
    }
  },
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function buildMockText(req: GenerateRequest): string {
  const sys = req.systemPrompt ?? ''
  const ko = /korean|한국어/i.test(sys) || !/english/i.test(sys)
  const repo = (req.prompt.match(/Repository:\s*(.+)/) ?? [])[1]?.trim() ?? 'this project'

  const note = ko
    ? '> 🧪 mock 미리보기입니다. `.env.local`에 실제 API 키를 넣으면 LLM 응답으로 대체됩니다.'
    : '> 🧪 This is a mock preview. Add real API keys in `.env.local` to replace it with LLM output.'

  if (/multiple-choice|퀴즈|quiz|json/i.test(sys)) {
    return `${note}\n\n\`\`\`json\n${JSON.stringify(
      {
        questions: [
          {
            q: ko
              ? `${repo}의 핵심 목적은 무엇인가요?`
              : `What is the main purpose of ${repo}?`,
            choices: ['A', 'B', 'C', 'D'],
            answer: 'A',
            explain: ko ? '(mock 해설)' : '(mock explanation)',
          },
        ],
      },
      null,
      2,
    )}\n\`\`\``
  }

  if (/roadmap|로드맵/i.test(sys)) {
    return ko
      ? `${note}\n\n## ${repo} 학습 로드맵\n\n1. **개요 파악** — README와 폴더 구조 훑어보기\n2. **핵심 개념** — 주요 모듈과 데이터 흐름 이해\n3. **직접 실행** — 로컬에서 빌드·구동해보기\n4. **응용** — 작은 기능을 추가하며 익히기`
      : `${note}\n\n## Learning roadmap for ${repo}\n\n1. **Overview** — skim the README and folder structure\n2. **Core concepts** — understand key modules and data flow\n3. **Run it** — build and launch locally\n4. **Extend** — add a small feature to learn by doing`
  }

  // 기본: 브리핑 / 번역 / Q&A 공통
  return ko
    ? `${note}\n\n**${repo} 요약**\n\n- 이 저장소는 학습용으로 탐색하기 좋은 구조를 가지고 있습니다.\n- README를 바탕으로 핵심 기능과 사용법을 파악할 수 있습니다.\n- 난이도: **입문~중급** (예시)\n\n실제 응답은 선택한 LLM 프로바이더가 생성합니다.`
    : `${note}\n\n**Summary of ${repo}**\n\n- This repository is well-structured for learning and exploration.\n- The README outlines the core features and usage.\n- Difficulty: **Beginner–Intermediate** (sample)\n\nThe real answer is generated by the selected LLM provider.`
}
